<a href="https://colab.research.google.com/github/Luffyapo93/Practica/blob/main/practica_calificada1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EJERCICIO1

In [45]:
import numpy as np
import pandas as pd
print("1.------------------ \n")
# Crea un vector de números enteros del 1 al 20.
vector1 = np.arange(1, 21)
print(vector1)

print("\n 2.---------------- \n")
# Crea una matriz de 3x3 con valores aleatorios entre 0 y 1.
matriz_3x3 = np.random.rand(3, 3)
print(matriz_3x3)


print("\n 3.------------------------ \n")

# Crea un array de 10 números equidistantes entre 0 y 1.
array_equidistante = np.linspace(0, 1, 10)
print(array_equidistante)
print("\n 4.---------------------------- \n")

# Crea una matriz identidad de 6x6.
matriz_identidad = np.eye(6)
print(matriz_identidad)
print("\n 5.----------------------------- \n")

# Concatena dos vectores vertical y horizontalmente.
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
concat_vertical = np.vstack((vector_a, vector_b))
concat_horizontal = np.hstack((vector_a, vector_b))
print(concat_vertical)
print(concat_horizontal)

1.------------------ 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 2.---------------- 

[[0.99973259 0.61534742 0.726359  ]
 [0.99163755 0.45905109 0.93530699]
 [0.1468364  0.34493515 0.4191415 ]]

 3.------------------------ 

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

 4.---------------------------- 

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

 5.----------------------------- 

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


EJERCICIO 2

In [44]:
print("1.------------- \n")
vec1 = np.array([10, 20, 30])
vec2 = np.array([1, 2, 3])
print(vec1)
print(vec2)

print("\n 2.------------- \n")
# Suma, resta, multiplicación y división
suma = vec1 + vec2
resta = vec1 - vec2
multiplicacion = vec1 * vec2
division = vec1 / vec2
print(suma)
print(resta)
print(multiplicacion)
print(division)

print("\n 3.---------------- \n")
# Media, mediana y desviación estándar
media = np.mean(vec1)
mediana = np.median(vec1)
desviacion = np.std(vec1)
print(media)
print(mediana)
print(desviacion)

print("\n 4.--------------- \n")
# Normaliza un vector dividiendo por su valor máximo
normalizado = vec1 / np.max(vec1)
print(normalizado)

print("\n 5.------------------ \n")
# Índice del valor máximo y mínimo
indice_max = np.argmax(vec1)
indice_min = np.argmin(vec1)
print(indice_max)
print(indice_min)

print("\n 6.-------------------- \n")
# Multiplicación matricial 3x3
A = np.random.randint(1, 10, (3,3))
B = np.random.randint(1, 10, (3,3))
multiplicacion_matricial = np.matmul(A, B)
print(multiplicacion_matricial)


1.- 

[10 20 30]
[1 2 3]

 2.- 

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]

 3.- 

20.0
20.0
8.16496580927726

 4.- 

[0.33333333 0.66666667 1.        ]

 5.- 

2
0

 6.- 

[[ 54 134  88]
 [ 29 101  76]
 [ 55 139  96]]


EJERCICIO 3

In [46]:
print("1.------------- \n")
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(vector)

print("\n 2.------------- \n")
# Selecciona elementos pares
pares = vector[vector % 2 == 0]
print(pares)

print("\n 3.---------------- \n")
# Filtros
mayores_5 = vector[vector > 5]
iguales_cero = vector[vector == 0]
negativos = vector[vector < 0]
print(mayores_5)
print(iguales_cero)
print(negativos)

print("\n 4.--------------- \n")
# Media a valores mayores de 50
valores = np.array([20, 55, 60, 10, 80])
media_mayores_50 = np.mean(valores[valores > 50])
print(media_mayores_50)


1.------------- 

[ 1  2  3  4  5  6  7  8  9 10]

 2.------------- 

[ 2  4  6  8 10]

 3.---------------- 

[ 6  7  8  9 10]
[]
[]

 4.--------------- 

65.0


EJERCICIO 4

In [47]:
print("1.------------- \n")
# Reemplaza valores mayores que 5 con 0
v = np.random.randint(0, 10, 10)
v[v > 5] = 0
print(v)

print("\n 2.------------- \n")
# Operaciones booleanas
a = np.array([True, False, True])
b = np.array([False, True, True])
and_op = a & b
or_op = a | b
xor_op = a ^ b
print(and_op)
print(or_op)
print(xor_op)

print("\n 3.---------------- \n")
# Múltiplos de 3
x = np.arange(20)
multiplos_3 = x[x % 3 == 0]
cantidad_multiplos_3 = len(multiplos_3)
print(multiplos_3)
print(cantidad_multiplos_3)

print("\n 4.--------------- \n")
# Índices no nulos
vec = np.array([0, 1, 0, 3, 0, 5])
indices_no_nulos = np.nonzero(vec)
print(indices_no_nulos)

print("\n 5.-------------------- \n")
# Comprobar si todos son mayores a un valor
valor_usuario = 5
todos_mayores = np.all(vec > valor_usuario)
print(todos_mayores)


1.------------- 

[0 5 0 0 0 0 0 0 0 0]

 2.------------- 

[False False  True]
[ True  True  True]
[ True  True False]

 3.---------------- 

[ 0  3  6  9 12 15 18]
7

 4.--------------- 

(array([1, 3, 5]),)

 5.-------------------- 

False


EJERCICIO 5

In [48]:
print("1.------------- \n")
# Cuadrado de cada elemento
vec = np.array([1, 2, 3, 4])
cuadrado = vec ** 2
print(cuadrado)

print("\n 2.------------- \n")
# Raíz cuadrada de cada elemento
raiz_cuadrada = np.sqrt(vec)
print(raiz_cuadrada)

print("\n 3.---------------- \n")
# Función exponencial
potencia = 3
exponencial = np.power(vec, potencia)
print(exponencial)

print("\n 4.--------------- \n")
# Valores máximos y mínimos por fila
mat = np.random.randint(0, 100, (3, 4))
max_filas = np.max(mat, axis=1)
min_filas = np.min(mat, axis=1)
print(mat)
print(max_filas)
print(min_filas)

print("\n 5.-------------------- \n")
# Aplicar función sin
valores = np.linspace(0, np.pi, 10)
sin_resultados = np.sin(valores)
print(sin_resultados)

print("\n 6.-------------------- \n")
# Transpuesta
matriz_3x4 = np.arange(12).reshape(3, 4)
transpuesta = matriz_3x4.T
print(transpuesta)


1.------------- 

[ 1  4  9 16]

 2.------------- 

[1.         1.41421356 1.73205081 2.        ]

 3.---------------- 

[ 1  8 27 64]

 4.--------------- 

[[32 56 96 13]
 [57 53 34 17]
 [ 8 45 88 97]]
[96 57 97]
[13 17  8]

 5.-------------------- 

[0.00000000e+00 3.42020143e-01 6.42787610e-01 8.66025404e-01
 9.84807753e-01 9.84807753e-01 8.66025404e-01 6.42787610e-01
 3.42020143e-01 1.22464680e-16]

 6.-------------------- 

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


EJERCICIO 6

In [51]:
# Crear DataFrame
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'María', 'Jorge', 'Lucía', 'Pedro', 'Laura', 'Sofía', 'Andrés'],
    'Edad': [23, 30, 28, 22, 35, 27, 26, 24, 29, 31],
    'Ciudad': ['Lima', 'Cusco', 'Lima', 'Arequipa', 'Cusco', 'Lima', 'Arequipa', 'Cusco', 'Lima', 'Arequipa']
}
df = pd.DataFrame(data)

# Filtrar personas con más de 25 años
mayores_25 = df[df['Edad'] > 25]

# Añadir columna 'Ingresos' con cualquier valor
df['Ingresos'] = [2500, 3000, 2700, 2300, 3200, 2900, 2800, 2600, 3100, 3300]

# Promedio de edad
promedio_edad = df['Edad'].mean()

# Conteo de ciudades
conteo_ciudades = df['Ciudad'].value_counts()

# Agrupar por ciudad y obtener promedio de edad
promedio_edad_por_ciudad = df.groupby('Ciudad')['Edad'].mean()

# Ordenar por edad ascendente
orden_asc = df.sort_values('Edad')

# Ordenar por edad descendente
orden_desc = df.sort_values('Edad', ascending=False)

# Mostrar todos los resultados
print("1.---------------------------- \n")
print("DataFrame original:\n", df)
print("\n2.-------------------------- \n")
print("\nPersonas mayores de 25:\n", mayores_25)
print("\n3.--------------------------- \n")
print("\nPromedio de edad:", promedio_edad)
print("\n4.-------------------------- \n")
print("\nConteo de ciudades:\n", conteo_ciudades)
print("\n5.--------------------------------- \n")
print("\nPromedio de edad por ciudad:\n", promedio_edad_por_ciudad)
print("\n6.--------------------------------- \n")
print("\nOrdenado por edad (ascendente):\n", orden_asc)
print("\n7.-------------------- -------------\n")
print("\nOrdenado por edad (descendente):\n", orden_desc)


1.---------------------------- 

DataFrame original:
    Nombre  Edad    Ciudad  Ingresos
0     Ana    23      Lima      2500
1    Luis    30     Cusco      3000
2  Carlos    28      Lima      2700
3   María    22  Arequipa      2300
4   Jorge    35     Cusco      3200
5   Lucía    27      Lima      2900
6   Pedro    26  Arequipa      2800
7   Laura    24     Cusco      2600
8   Sofía    29      Lima      3100
9  Andrés    31  Arequipa      3300

2.-------------------------- 


Personas mayores de 25:
    Nombre  Edad    Ciudad
1    Luis    30     Cusco
2  Carlos    28      Lima
4   Jorge    35     Cusco
5   Lucía    27      Lima
6   Pedro    26  Arequipa
8   Sofía    29      Lima
9  Andrés    31  Arequipa

3.--------------------------- 


Promedio de edad: 27.5

4.-------------------------- 


Conteo de ciudades:
 Ciudad
Lima        4
Cusco       3
Arequipa    3
Name: count, dtype: int64

5.--------------------------------- 


Promedio de edad por ciudad:
 Ciudad
Arequipa    26.333333

EJERCICIO 7

In [63]:
import pandas as pd
# Cargar archivo (reemplaza 'archivo.csv' con el nombre real)
df = pd.read_excel('/content/universidad.xlsx')  # o usa pd.read_excel() si es .xlsx

# Filtro 1: Ingeniería en sistemas
ing_sistemas = df[df['Carrera'] == 'Ing. en sistemas']
cantidad_sistemas = len(ing_sistemas)

# Filtro 2: Ingeniería en derecho
ing_derecho = df[df['Carrera'] == 'Lic. en derecho']
cantidad_derecho = len(ing_derecho)

# Convertir la columna 'Inscripción' a datetime (asegúrate de usar el formato correcto)
df['Inscripción'] = pd.to_datetime(df['Inscripción'], dayfirst=True)

# Filtrar inscritos en el año 2015
inscritos_2015 = df[df['Inscripción'].dt.year == 2015]
cantidad_2015 = len(inscritos_2015)

print("Cantidad inscritos en 2015:", cantidad_2015)


# Filtro 4: Alumnos de 1° y 2° semestre
semestres_1_2 = df[df['Semestre'].isin([1, 2])]
cantidad_1_2 = len(semestres_1_2)

# Mostrar resultados
print("1.---------------------------- \n")
print("Cantidad en Ing. en sistemas:", cantidad_sistemas)
print("\n2.---------------------------- \n")
print("Cantidad en Lic. en derecho:", cantidad_derecho)
print("\n3.---------------------------- \n")
print("Cantidad inscritos en 2015:", cantidad_2015)
print("\n4.---------------------------- \n")
print("Cantidad en 1 y 2 semestre:", cantidad_1_2)


Cantidad inscritos en 2015: 23
1.---------------------------- 

Cantidad en Ing. en sistemas: 13

2.---------------------------- 

Cantidad en Lic. en derecho: 17

3.---------------------------- 

Cantidad inscritos en 2015: 23

4.---------------------------- 

Cantidad en 1 y 2 semestre: 22
